version: '3'
services:
  app:
    image: macielbombonato/docker-jmeter:latest
    container_name: jmeter
    environment:
        - PROPS_PATH=user.properties
        - JMX_FILE=YourTestPlan.jmx
        - YML_FILE=user.yml
        - JTL_FILE=kpi.jtl
        - RUN_TEST=true
        - USE_BLAZE_METER=false
        - MERGE_RESULTS=false
        - REPORT_FOLDER=report
        - HEAP=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
    volumes:
        - .:/opt/jmx
        - ./results:/opt/results
